version: "3.5"
services:
    testsecurity:
        image: openjdk:9
        container_name: java-container-testsecurity
        expose:
            - "8080"
        ports:
            - "8080:8080"
        volumes:
            - "./target:/app"
        command: java -jar /app/testsecurity-1.0-SNAPSHOT.jar
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql-testsecurity
        ports:
            - "3306:3306"
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: test
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

networks:
    default:
       name: testsecurity
       driver: bridge